# Generated by Django 3.2.7 on 2021-09-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_issueschema_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
