# Generated by Django 3.2.7 on 2021-09-30 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='schema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.issueschema'),
        ),
        migrations.AlterField(
            model_name='issueschemafield',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.fieldtype'),
        ),
    ]
