# Generated by Django 3.2.7 on 2021-09-30 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20210930_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('CF', 'Choice field'), ('MCF', 'Multiselect choice field'), ('L', 'Label'), ('ML', 'Multiselect label'), ('D', 'Date'), ('T', 'Time'), ('Du', 'Duration'), ('DT', 'Date with time')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='FieldValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=500, null=True)),
                ('default_value', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.fieldtype')),
            ],
        ),
    ]
