# Generated by Django 3.2 on 2021-06-15 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0002_group_profile_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='mnemonic',
            field=models.CharField(default='default_mnemonic_name', max_length=50),
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='commons.group'),
        ),
    ]
